### ISSUE TITLE
[UI / Bug] log out on map view results in Rails error

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#130]
Once you've logged in to administrate, a "log out" options appears on the front page, and the sidebar in `/home/`.

"Log out" on the front page works just fine, but the sidebar link in `/home/` results in the following error:

`No route matches [GET] "/users/sign_out"`

On both locations, the link is the same: `/users/sign_out`

**Comment by LizPrescott** [comment]
I can try this one.

**Comment by mirandawang** [comment]
@LizPrescott It would be awesome if you could still take a look at this issue! :)
I just "closed" it by removing that link and replacing it with a link back to the Welcome page.
The tricky bit here is the connection between Rails & React. You can't just use the URL "/users/sign_out" because it needs to be a DELETE http request to that URL with the user's ID. I recommend that we look into using a library like axios or fetch to send that DELETE request because there is currently no way to do it thru a form. We could do ajax, but the overhead of the jquery library might be a bit too much for just one HTTP request. 
When making the DELETE request, we DO have access to the current user model, so we can easily pass the `this.props.user.id` value to the request.

**Comment by mirandawang** [comment]
@LizPrescott are you still able to work on this one? :)

**Comment by LizPrescott** [comment]
Sure! I can look again this afternoon. Will let you know if I’m stumped.

**Comment by LizPrescott** [comment]
Found this! https://medium.com/@iamjane/devise-with-react-webpacker-and-rails-dacbf9ae0233

**Comment by rudokemper** [comment]
Reviewing this issue, it seems like we no longer have a "log out" option in the sidebar, so this issue is moot. For me, this is a sufficient solution. The user can return to the home screen to log out and/or switch credentials.

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
