### ISSUE TITLE
[CMS] Add ability to set map extent, page title, logo, background, other basic stylistic elements via Administrate

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#166]
We should have the ability to allow the admin user to upload their logo, set the background for the welcome screen, and some basic CSS properties like color scheme via the Administrate back end. (Currently, these have to be hard coded.)

**Comment by Bootjack** [comment]
In order to allow Administrate to manage this, we should create a Theme model to represent the color values and uploaded images.

Then we can inject CSS in a view partial that defines `.themed .componentName` rules which will use the values from the Theme model to populate things like primary and secondary colors, and maybe certain background images.

**Comment by rudokemper** [comment]
In addition to stylistic element, it would be good to allow the user to define the map extent (currently hard-coded in lines 25-26 of `Map.jsx`.

**Comment by rudokemper** [comment]
For the map, the zoom extent of the fly-to would be nice as well.

**Comment by mirandawang** [comment]
To keep this scoped, let's start with just one of these - like the logo!

Once we have a workflow built out, we can add in more features.

**Comment by mirandawang** [comment]
closing for now; moving details to issue google doc
