### ISSUE TITLE
[UI] Reset sidebar scroll position to top when interacting with filters

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#257]
When you scroll down in the sidebar, and interact with the filters to change the sidebar content, the sidebar stays put in the same vertical position, although the content has changed. 

The sidebar should reset back to the top when a filter has been selected.

@mirandawang may have some code to share that can be modified to do the job :)

**Comment by MxOliver** [comment]
Can I look into this?

**Comment by rudokemper** [comment]
That would be great, Oliver! :)

**Comment by MxOliver** [comment]
Just a clarification, when you click the filter you'd like the sidebar to scroll so that story is at the top of the sidebar? Or should it reset back to the very top regardless of what story was clicked? Like if Miranda is at the top and I click the Kalimar story, should it scroll so Kalimar is up top, or should it scroll back to Miranda to reset to the top?

**Comment by rudokemper** [comment]
Good question! I would say the very top, always.



Rudo Kemper
Manager, Mapping & Programs Support
Amazon Conservation Team - US
4211 N. Fairfax Drive, Arlington, VA 22203
Ofc: (+1) 703-522-4684
rkemper@amazonteam.org| www.amazonteam.org
-------- Original message --------

**Comment by mirandawang** [comment]
closed here https://github.com/Terrastories/terrastories/pull/336
