### ISSUE TITLE
[Bug] Stories showing in StoryList even when there is no Place selected for them

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#578]
**Describe the bug**
Currently, Stories that don't have Places selected are showing in the StoryList (sidebar). This goes counterintuitive to the UX experience of being able to click on stories to navigate to the related places.

**To Reproduce**
1. Create a story
2. Don't select a place
3. Save the story
4. Navigate to the map view
5. The story should show up on the list, and clicking on it does nothing.

EDIT: the same thing happens if you _do_ select a place, but one without latitude or longitude saved.

**Expected behavior**
The story should not show up on the StoryList if there is no place selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/31662219/103089825-37121700-45bd-11eb-8249-49eb73264865.png)

**Comment by lauramosher** [comment]
This could be solved by either:

1. Removing stories without places from the scope, or
2. Adding a validation to ensure that a story has a place.

I'd recommend going route 2 since a story should always have a place.

**Comment by rudokemper** [comment]
One argument in favor of #1 is that in terms of the workflow, a user might be adding a Story before considering the Place, and wants to save it as as a draft. Or, users are adding Stories without know about the Places yet, and add the Places later after they figure out where the Stories took place.

**Comment by lauramosher** [comment]
If that's a common flow we can expect users to take, there should probably be a feature request for this rather than a bug.

> This goes counterintuitive to the UX experience of being able to click on stories to navigate to the related places.

Since the experience for mapping stories to a map objectively requires a Place, a Story should be required to have a Place and solved with a validation. This will resolve the bug and ensure that the experience is preserved.

Option 1 would work, but it only patches one problem and has potential to introduce many more. We'd be "hiding" stories without really telling the user WHY those stories aren't showing on the map with no real indication in the Admin area or Map area that a story requires a place in order to be visible on the map.

I'd still suggest going with option 2 to patch this bug. It'll be a little annoying at the beginning, but is more true-to-requirements for how we expect Place and Story to work. In addition, we can log a new feature request that introduces Save as Draft for Stories. This way, we can require the validation if the story is "published" (regardless of permission level) and allow it to be saved in draft state without a Place. Once we have a hard distinction of draft (possibly without place) and published (please show on map) that is user-selected, we can update the policy scope to only return published stories (rather than a hard coded criteria such as missing a place).

**Comment by rudokemper** [comment]
Thanks @lauramosher. That all makes a lot of sense, and I agree with your suggested approach here.

**Comment by EitanFuturo** [comment]
I've made a [PR](https://github.com/Terrastories/terrastories/pull/661) to solve this issue according to the previous conversation, hope it's helpful.
